server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/ 
  #    suffix: .html 
  mvc:
    static-path-pattern: /static/** 
    view:
      suffix: .html
  resources:
    static-locations: classpath:/templates
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 100  # 最大
      # 连接超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      # 当连接空闲时，是否执行连接测试
      test-while-idle: true
      # 当从连接池借用连接时，是否测试该连接
      test-on-borrow: false
      # 在连接归还到连接池时是否测试该连接
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 合併多個DruidDataSource的監控資料
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j,config
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      # 是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 10
      # 根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html
      # http://loacalhsot:8081/druid
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # IP白名单(没有配置或者为空，则允许所有访问)
        # 白名单逻辑已经改了，如果不配或为空，那么只能在本地访问
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        login-username: admin
        login-password: admin

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:com/durian/first/*/mapper/*.xml
  #扫描实体类,多个package用逗号或者分号分隔
  type-aliases-package: com.durian.first.entity.*
  configuration:
    cache-enabled: false
  global-config:
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      # 表名前缀
      table-prefix: null
      #逻辑删除配置
      logic-not-delete-value: 1 #删除前
      logic-delete-value: 0  #删除后
